import BigEye_California from './../../images/BigEye-California.jpg'
import California from './../../images/California.jpg'
import Nija_roru from './../../images/Nija-roru.jpg'
import Osaka_maki from './../../images/Osaka-maki.jpg'
import Royal_roll from './../../images/Royal-roll.jpg'
import Sapporo_Maki from './../../images/Sapporo-Maki.jpg'
import Shake_Roru from './../../images/Shake-Roru.jpg'
import Shake_teriyaki from './../../images/Shake-teriyaki.jpg'
import Unagi_Philadelphia from './../../images/Unagi-Philadelphia.jpg'

export const rolls = [
  {id: 1,
    src: BigEye_California,
    alt: 'BigEye-California',
    name: 'BigEye Калифорния',
    structure: 'мясо краба, огурец, авокадо, масаго, тунец, васаби',
    price: 499,
  },
  {id: 2,
    src: California,
    alt: 'California',
    name: 'Калифорния',
    structure: 'мясо краба, огурец, авокадо, тобико, васаби',
    price: 499,
  },
  {id: 3,
    src: Nija_roru,
    alt: 'Nija-roru',
    name: 'Нидзя рору',
    structure: 'копченый угорь, лосось, огурец, сливочный сыр, тамаго, тобико, васаби, соус "Спайси"',
    price: 377,
  },
  {id: 4,
    src: Osaka_maki,
    alt: 'Osaka-maki',
    name: 'Осака маки',
    structure: 'лосось, сливочный сыр, огурец, васаби',
    price: 499,
  },
  {id: 5,
    src: Royal_roll,
    alt: 'Royal-roll',
    name: 'Royal roll',
    structure: 'мясо краба, огурец, авокадо, масаго, тунец, васабиопаленный ролл со сливочным сыром, тартаром из лосося и копченого угря, с красной икрой, соусами «Спайси» и «Унаги», васаби',
    price: 497,
  },
  {id: 6,
    src: Sapporo_Maki,
    alt: 'Sapporo-Maki',
    name: 'Саппоро маки',
    structure: 'обжаренный лосось «Бури», манго, авокадо, сливочный сыр, васаби',
    price: 387,
  },
  {id: 7,
    src: Shake_Roru,
    alt: 'Shake-Roru',
    name: 'Сякэ рору',
    structure: 'лосось, васаби',
    price: 267,
  },
  {id: 8,
    src: Shake_teriyaki,
    alt: 'Shake-teriyaki',
    name: 'Сякэ терияки',
    structure: 'лосось, снежный краб, авокадо, огурец, кунжут, соус «Терияки», васаби',
    price: 417,
  },
  {id: 9,
    src: Unagi_Philadelphia,
    alt: 'Unagi-Philadelphia',
    name: 'Унаги Филадельфия',
    structure: 'копченый угорь, сливочный сыр, спайси лосось «Бури», авокадо, тобико, тамаго, васаби',
    price: 477,
  },
];
